# Generated by Django 4.2.7 on 2023-11-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonot', '0002_note_delete_userfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='#FFFFCC', max_length=7),
        ),
    ]
